### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by ghost** [asnelt/derandom#1]
So I just checked out this app
And I'm a bit confused.
I typed in 1 2 3 4 5 6 7 etc (seperated by a new line) You'd expect it to say 8 9 10 etc
So how exactly can this be used?
In no way does it output any logical number that you'd expect in this sequence even if it's just simple one like adding 1 every time.

**Comment by asnelt** [comment]
Thanks for your interest in this Derandom.
You are right, this app does not detect and predict sequences like 1 2 3 4 ... It detects and predicts pseudo random number generators like the linear congruential generator (https://en.wikipedia.org/wiki/Linear_congruential_generator). Right now, this is the only class of generators implemented, but others will follow soon. So you can take the output of a pseudo random number generator like Java's Random.nextInt() and use that as input for Derandom (you can send it to Derandom using a socket). Derandom will then detect the coefficients and seed of the linear congruential generator and predict following numbers. An example sequence would be:
1412437139
1552322984
168467398
1111755060
-928874005

**Comment by ghost** [comment]
Thanks for the quick reply!
That seems interesting, does that mean it can predict numbers generated for secure connections and encryption? 

I previously thought the algorithms you can select are prediction algorithms but they're just generator algorithms that you can derandomise. That makes more sense indeed :)

**Comment by asnelt** [comment]
If the connections and encryption are secured with a common linear congruential generator, then yes, Derandom can predict numbers for them. Ideally, such security related methods should not rely on a linear congruential generator, though. In Java, for instance, there is SecureRandom for security related random numbers. Nevertheless, simple pseudo random number generators are widely applied for many purposes.
Another drawback of the app right now is the need for observing the complete random number from the generator. In coming releases I plan to also implement support for incomplete observations (where only n bits of the number are observed, n < 32) and missing elements in the sequence (where you could leave out for instance the second number 1552322984 in the example sequence). More to come.

**Comment by ghost** [comment]
Thanks for clearing that up for me :) seems like a great little tool for all sorts of scenarios, I'll stay tuned for that. Perhaps you could add a way to use a custom algorithm, I can't think of a way thay would be usefull but surely someone else can.

Also thanks for making it open-source for others to learn from!
